AllCops:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'test/factories/*'
    - !ruby/regexp /old_and_unused\.rb$/

Metrics/LineLength:
  Max: 100

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'