AllCops:
  NewCops: enable
  
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'spec/factories/*'
    - !ruby/regexp /old_and_unused\.rb$/

Layout/LineLength:
  Max: 100

Lint/MissingSuper:
  Exclude:
    - 'app/services/**/*'